export const ar = {
  totalleads: "إجمالي العملاء المحتملين",
  numberofmeeting: "عدد الاجتماعات",
  closingofthemonth: "إغلاق الشهر",
  lastmonthclosed: "مغلق الشهر الماضي",
  dashboard: "لوحة القيادة",
  leads: "العملاء المحتملين",
  servicetickets: "Service Tickets",
  leadList: "قائمة العملاء المحتملين",
  piplines: "خط الأنابيب",
  meetings: "الاجتماعات",
  bookings: "الحجوزات",
  products: "منتجات",
  users: "المستخدمون",
  usersaccess: "وصول المستخدمين",
  tickets: "التذاكر",
  ProductManagement: "إدارة المنتج",
  ProductName: "اسم المنتج",
  Description: "وصف",
  Price: "سعر",
  CreatedAt: "تم الإنشاء في",
  Actions: "الإجراءات",
  Edit: "يحرر",
  Delete: "يمسح",
  AddProduct: "أضف منتج",
  EditProduct: "تحرير المنتج",
  SaveChanges: "حفظ التغييرات",
  Cancel: "يلغي",
  DeleteProduct: "حذف المنتج",
  LeadsManagement: "إدارة العملاء المتوقعين",
  Name: "اسم",
  Email: "بريد إلكتروني",
  Phone: "هاتف",
  Value: "قيمة",
  Priority: "أولوية",
  LastContact: "آخر اتصال",
  Actions: "الإجراءات",
  AddLeadList: "إضافة قائمة العملاء المحتملين",
  EditLead: "تحرير الرصاص",
  Noleadsfound: "لم يتم العثور على أي خيوط",
  "Open menu": "فتح القائمة",
  Rowsperpage: "عدد الصفوف في الصفحة",
  Previous: "سابق",
  Next: "التالي",
  Page: "صفحة",
  of: "ل",
  AddNewLeadList: "إضافة قائمة عملاء محتملين جديدة",
  FirstName: "الاسم الأول",
  LastName: "اسم العائلة",
  ExistingUsers: "المستخدمون الحاليون",
  LeadSource: "مصدر الرصاص",
  Remark: "ملاحظة",
  ExpectedRevenue: "الإيرادات المتوقعة",
  Product: "منتج",
  Pipeline: "خط أنابيب",
  PipelineStages: "مراحل خطوط الأنابيب",
  AssignTo: "تعيين ل",
  AddLead: "أضف الرصاص",
  High: "عالي",
  Medium: "واسطة",
  Low: "قليل",
  "Updatethedetailsforthislead.": "تحديث التفاصيل لهذا العميل المحتمل",
  ConfirmDeletion: "تأكيد الحذف",
  "Areyousureyouwanttodeletethislead?Thisactioncannotbeundone.":
    "هل أنت متأكد أنك تريد حذف هذا العميل المحتمل؟ لا يمكن التراجع عن هذا الإجراء.",
  "Search...": "يبحث ...",
  Nothreadsfound: "لم يتم العثور على المواضيع",
  SelectCustomer: "حدد العميل",
  Selectpriority: "حدد الأولوية",
  SelectProduct: "حدد المنتج",
  SelectPipeline: "حدد خط الأنابيب",
  SelectStage: "حدد المرحلة",
  SelectAgent: "حدد الوكيل",
  Meetings: "الاجتماعات",
  AddMeetings: "إضافة الاجتماعات",
  AddNewMeeting: "إضافة اجتماع جديد",
  Actions: "الإجراءات",
  Title: "عنوان",
  StartDate: "تاريخ البدء",
  EndDate: "تاريخ الانتهاء",
  Description: "وصف",
  FillDetails: "املأ التفاصيل لإنشاء اجتماع جديد",
  MeetingUrl: "رابط الاجتماع",
  Add: "يضيف",
  AddOtherRecipents: "إضافة وصفات أخرى",
  Join: "ينضم",
  CreateNewPipeline: "إنشاء خط أنابيب جديد",
  PipelineName: "اسم خط الأنابيب",
  PipelineStages: "مراحل خط الأنابيب",
  AddStage: "أضف مرحلة",
  CreatePipeline: "إنشاء خط أنابيب",
  NoPipelineFound:
    "لم يتم العثور على أي خطوط أنابيب. أنشئ خط الأنابيب الأول الخاص بك!",
  CreatePipeline: "إنشاء خط أنابيب",
  PipelineManagement: "إدارة خطوط الأنابيب",
  YourPipelines: "خطوط الأنابيب الخاصة بك",
  totalleads: "إجمالي العملاء المحتملين",
  numberofmeeting: "عدد الاجتماعات",
  closingofthemonth: "إغلاق الشهر",
  lastmonthclosed: "مغلق الشهر الماضي",
  dashboard: "لوحة القيادة",
  leads: "العملاء المحتملين",
  leadList: "قائمة العملاء المحتملين",
  piplines: "خط الأنابيب",
  meetings: "الاجتماعات",
  bookings: "الحجوزات",
  products: "منتجات",
  users: "المستخدمون",
  usersaccess: "وصول المستخدمين",
  tickets: "التذاكر",
  ProductManagement: "إدارة المنتج",
  ProductName: "اسم المنتج",
  Description: "وصف",
  Price: "سعر",
  CreatedAt: "تم الإنشاء في",
  Actions: "الإجراءات",
  Edit: "يحرر",
  Delete: "يمسح",
  AddProduct: "أضف منتج",
  EditProduct: "تحرير المنتج",
  SaveChanges: "حفظ التغييرات",
  Cancel: "يلغي",
  DeleteProduct: "حذف المنتج",
  LeadsManagement: "إدارة العملاء المتوقعين",
  Name: "اسم",
  Email: "بريد إلكتروني",
  Phone: "هاتف",
  Value: "قيمة",
  Priority: "أولوية",
  LastContact: "آخر اتصال",
  Actions: "الإجراءات",
  AddLeadList: "إضافة قائمة العملاء المحتملين",
  EditLead: "تحرير الرصاص",
  Noleadsfound: "لم يتم العثور على أي خيوط",
  "Open menu": "فتح القائمة",
  Rowsperpage: "عدد الصفوف في الصفحة",
  Previous: "سابق",
  Next: "التالي",
  Page: "صفحة",
  of: "ل",
  AddNewLeadList: "إضافة قائمة عملاء محتملين جديدة",
  FirstName: "الاسم الأول",
  LastName: "اسم العائلة",
  ExistingUsers: "المستخدمون الحاليون",
  LeadSource: "مصدر الرصاص",
  Remark: "ملاحظة",
  ExpectedRevenue: "الإيرادات المتوقعة",
  Product: "منتج",
  Pipeline: "خط أنابيب",
  PipelineStages: "مراحل خطوط الأنابيب",
  AssignTo: "تعيين ل",
  AddLead: "أضف الرصاص",
  High: "عالي",
  Medium: "واسطة",
  Low: "قليل",
  "Updatethedetailsforthislead.": "تحديث التفاصيل لهذا العميل المحتمل",
  ConfirmDeletion: "تأكيد الحذف",
  "Areyousureyouwanttodeletethislead?Thisactioncannotbeundone.":
    "هل أنت متأكد أنك تريد حذف هذا العميل المحتمل؟ لا يمكن التراجع عن هذا الإجراء.",
  "Search...": "يبحث ...",
  Nothreadsfound: "لم يتم العثور على المواضيع",
  SelectCustomer: "حدد العميل",
  Selectpriority: "حدد الأولوية",
  SelectProduct: "حدد المنتج",
  SelectPipeline: "حدد خط الأنابيب",
  SelectStage: "حدد المرحلة",
  SelectAgent: "حدد الوكيل",
  "Searchleads...": "يؤدي البحث...",
  SampleImportSheet: "نموذج ورقة الاستيراد",
  AddLead: "أضف الرصاص",
  ImportExcelData: "استيراد بيانات اكسل",
  ImportCRMData: "استيراد بيانات إدارة علاقات العملاء",
  UploadanExcelorCSVfile:
    "قم بتحميل ملف Excel (.xlsx، .xls) أو ملف CSV لاستيراد البيانات إلى نظام CRM الخاص بك.",
  ChooseExcelfile: "اختر ملف إكسل",
  Clicktoupload: "انقر للتحميل",
  ordraganddrop: "أو السحب والإفلات",
  ExcelorCSV: "ملفات Excel أو CSV فقط",
  "Uploading...": "جارٍ التحميل...",
  "Uploadsuccessful!": "تم التحميل بنجاح!",
  Uploadfailed: "فشل التحميل. يُرجى المحاولة مرة أخرى.",
  ID: "بطاقة تعريف",
  Customer: "عميل",
  Service: "خدمة",
  DateTime: "التاريخ والوقت",
  Status: "حالة",
  Amount: "كمية",
  Bookings: "الحجوزات",
  SearchBookings: "بحث في الحجوزات...",
  ProductManagement: "إدارة المنتج",
  AddProduct: "أضف منتج",
  SearchProducts: "بحث عن المنتجات...",
  ProductName: "اسم المنتج",
  Price: "سعر",
  CreatedAt: "تم الإنشاء في",
  UserManagement: "إدارة المستخدم",
  AddUser: "إضافة مستخدم",
  SearchUsers: "البحث في المستخدمين...",
  Role: "دور",
  SalesManager: "مدير المبيعات",
  SalesExecutive: "تنفيذي مبيعات",
  Customer: "عميل",
  SureWantToDelete: "هل أنت متأكد من أنك تريد الحذف؟",
  DeleteUser: "حذف المستخدم",
  NoUserFound: "لم يتم العثور على مستخدم...",
  Password: "كلمة المرور",
  SelectRole: "حدد الدور",
};
