export const en = {
  totalleads: "Total Leads",
  numberofmeeting: "Number Of Meeting",
  closingofthemonth: "Closing Of The Month",
  lastmonthclosed: "Last Month Closed",
  dashboard: "Dashboard",
  leads: "Leads",
  servicetickets: "Service Tickets",
  leadList: "Lead List",
  piplines: "Piplines",
  meetings: "Meetings",
  bookings: "Bookings",
  products: "Products",
  users: "Users",
  usersaccess: "Users Access",
  tickets: "Tickets",
  ProductManagement: "Product Management",
  ProductName: "Product Name",
  Description: "Description",
  Price: "Price",
  CreatedAt: "Created At",
  Actions: "Actions",
  Edit: "Edit",
  Delete: "Delete",
  AddProduct: "Add Product",
  EditProduct: "Edit Product",
  SaveChanges: "Save Changes",
  Cancel: "Cancel",
  DeleteProduct: "Delete Product",
  LeadsManagement: "Leads Management",
  Name: "Name",
  Email: "Email",
  Phone: "Phone",
  Value: "Value",
  Priority: "Priority",
  LastContact: "Last Contact",
  Actions: "Actions",
  AddLeadList: "Add Lead List",
  EditLead: "Edit Lead",
  Noleadsfound: "No leads found",
  Openmenu: "Open menu",
  Rowsperpage: "Rows per page",
  Previous: "Previous",
  Next: "Next",
  Page: "Page",
  of: "of",
  AddNewLeadList: "Add New Lead List",
  FirstName: "First Name",
  LastName: "Last Name",
  ExistingUsers: "Existing Users",
  LeadSource: "Lead Source",
  Remark: "Remark",
  ExpectedRevenue: "Expected Revenue",
  Product: "Product",
  Pipeline: "Pipeline",
  PipelineStages: "Pipeline Stages",
  AssignTo: "Assign To",
  AddLead: "Add Lead",
  High: "High",
  Medium: "Medium",
  Low: "Low",
  "Updatethedetailsforthislead.": "Update the details for this lead.",
  ConfirmDeletion: "Confirm Deletion",
  "Areyousureyouwanttodeletethislead?Thisactioncannotbeundone.":
    "Are you sure you want to delete this lead? This action cannot be undone.",
  "Search...": "Search...",
  Nothreadsfound: "No threads found",
  SelectCustomer: "Select Customer",
  Selectpriority: "Select priority",
  SelectProduct: "Select Product",
  SelectPipeline: "Select Pipeline",
  SelectStage: "Select Stage",
  SelectAgent: "Select Agent",
  Meetings: "Meetings",
  AddMeetings: "Add Meetings",
  AddNewMeeting: "AddNewMeeting",
  Actions: "Actions",
  Title: "Title",
  StartDate: "StartDate",
  EndDate: "EndDate",
  Description: "Description",
  FillDetails: "Fill in the details to create a new meeting",
  MeetingUrl: "Meeting Url",
  Add: "Add",
  AddOtherRecipents: "Add Other Recipents",
  Join: "Join",
  CreateNewPipeline: "Create New Pipeline",
  PipelineName: "Pipeline Name",
  PipelineStages: "Pipe Line Stages",
  AddStage: "Add Stage",
  CreatePipeline: "Create Pipeline",
  NoPipelineFound: "No pipelines found. Create your first pipeline!",
  CreatePipeline: "Create Pipeline",
  PipelineManagement: "Pipeline Management",
  YourPipelines: "Your Pipelines",
  totalleads: "Total Leads",
  numberofmeeting: "Number Of Meeting",
  closingofthemonth: "Closing Of The Month",
  lastmonthclosed: "Last Month Closed",
  dashboard: "Dashboard",
  leads: "Leads",
  leadList: "Lead List",
  piplines: "Piplines",
  meetings: "Meetings",
  bookings: "Bookings",
  products: "Products",
  users: "Users",
  usersaccess: "Users Access",
  tickets: "Tickets",
  ProductManagement: "Product Management",
  ProductName: "Product Name",
  Description: "Description",
  Price: "Price",
  CreatedAt: "Created At",
  Actions: "Actions",
  Edit: "Edit",
  Delete: "Delete",
  AddProduct: "Add Product",
  EditProduct: "Edit Product",
  SaveChanges: "Save Changes",
  Cancel: "Cancel",
  DeleteProduct: "Delete Product",
  LeadsManagement: "Leads Management",
  Name: "Name",
  Email: "Email",
  Phone: "Phone",
  Value: "Value",
  Priority: "Priority",
  LastContact: "Last Contact",
  Actions: "Actions",
  AddLeadList: "Add Lead List",
  EditLead: "Edit Lead",
  Noleadsfound: "No leads found",
  Openmenu: "Open menu",
  Rowsperpage: "Rows per page",
  Previous: "Previous",
  Next: "Next",
  Page: "Page",
  of: "of",
  AddNewLeadList: "Add New Lead List",
  FirstName: "First Name",
  LastName: "Last Name",
  ExistingUsers: "Existing Users",
  LeadSource: "Lead Source",
  Remark: "Remark",
  ExpectedRevenue: "Expected Revenue",
  Product: "Product",
  Pipeline: "Pipeline",
  PipelineStages: "Pipeline Stages",
  AssignTo: "Assign To",
  AddLead: "Add Lead",
  High: "High",
  Medium: "Medium",
  Low: "Low",
  "Updatethedetailsforthislead.": "Update the details for this lead.",
  ConfirmDeletion: "Confirm Deletion",
  "Areyousureyouwanttodeletethislead?Thisactioncannotbeundone.":
    "Are you sure you want to delete this lead? This action cannot be undone.",
  "Search...": "Search...",
  Nothreadsfound: "No threads found",
  SelectCustomer: "Select Customer",
  Selectpriority: "Select priority",
  SelectProduct: "Select Product",
  SelectPipeline: "Select Pipeline",
  SelectStage: "Select Stage",
  SelectAgent: "Select Agent",
  "Searchleads...": "Search leads...",
  SampleImportSheet: "Sample Import Sheet",
  AddLead: "Add Lead",
  ImportExcelData: "Import Excel Data",
  ImportCRMData: "Import CRM Data",
  UploadanExcelorCSVfile:
    "Upload an Excel file (.xlsx, .xls) or CSV file to import data into your CRM.",
  ChooseExcelfile: "Choose Excel file",
  Clicktoupload: "Click to upload",
  ordraganddrop: "or drag and drop",
  ExcelorCSV: "Excel or CSV files only",
  "Uploading...": "Uploading...",
  "Uploadsuccessful!": "Upload successful!",
  Uploadfailed: "Upload failed. Please try again.",
  ID: "ID",
  Customer: "Customer",
  Service: "Service",
  DateTime: "Date&Time",
  Status: "Status",
  Amount: "Amount",
  Bookings: "Bookings",
  SearchBookings: "Search Bookings...",
  UserManagement: "User Management",
  AddUser: "Add User",
  SearchUsers: "Search Users...",
  Role: "Role",
  SalesManager: "Sales Manager",
  SalesExecutive: "Sales Executive",
  Customer: "Customer",
  SureWantToDelete: "are you sure want to delete",
  DeleteUser: "Delete User",
  NoUserFound: "No User Found...",
  Password: "Password",
  SelectRole: "Select Role",
};
