'use client'

import React from 'react'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import * as Collapsible from '@radix-ui/react-collapsible'
import { ChevronDown } from 'lucide-react'
import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import Link from "next/link"

interface PayslipProps {
  employee: {
    name: string
    id: string
    designation: string
    department: string
    joiningDate: string
  }
  earnings: { type: string; amount: number }[]
  deductions: { type: string; amount: number }[]
}

export default function Payslip({ employee, earnings, deductions }: PayslipProps) {
  const totalEarnings = earnings.reduce((sum, e) => sum + e.amount, 0)
  const totalDeductions = deductions.reduce((sum, d) => sum + d.amount, 0)
  const netPay = totalEarnings - totalDeductions


const handleDownloadPDF = () => {
  const doc = new jsPDF({
    orientation: "p",
    unit: "mm",
    format: "a4",
  })

  // --- HEADER SECTION ---
  doc.setFillColor(30, 64, 175) // Blue bar
  doc.rect(0, 0, 210, 30, "F")
  doc.setTextColor(255, 255, 255)
  doc.setFont("helvetica", "bold")
  doc.setFontSize(18)
  doc.text("ACME HRMS PVT. LTD.", 14, 18)
  doc.setFontSize(12)
  doc.text("Employee Payslip - October 2025", 150, 18, { align: "right" })

  // --- EMPLOYEE INFO BOX ---
  doc.setTextColor(0, 0, 0)
  doc.setFontSize(12)
  doc.setFont("helvetica", "bold")
  doc.text("Employee Details", 14, 42)
  doc.setDrawColor(30, 64, 175)
  doc.line(14, 44, 196, 44)

  doc.setFont("helvetica", "normal")
  doc.setFontSize(10)
  const leftStart = 14
  const rightStart = 110
  let y = 52
  doc.text(`Name: ${employee.name}`, leftStart, y)
  doc.text(`Employee ID: ${employee.id}`, rightStart, y)
  y += 7
  doc.text(`Designation: ${employee.designation}`, leftStart, y)
  doc.text(`Department: ${employee.department}`, rightStart, y)
  y += 7
  doc.text(`Joining Date: ${employee.joiningDate}`, leftStart, y)

  // --- EARNINGS TABLE ---
  const earningsData = earnings.map(e => [e.type, `₹${e.amount.toLocaleString()}`])
  autoTable(doc, {
    startY: y + 10,
    head: [["Earnings", "Amount (₹)"]],
    body: [...earningsData, ["Total Earnings", `₹${totalEarnings.toLocaleString()}`]],
    theme: "grid",
    headStyles: { fillColor: [30, 64, 175], halign: "center", textColor: 255 },
    styles: { fontSize: 10, halign: "center" },
  })

  // --- DEDUCTIONS TABLE ---
  const afterEarnings = (doc as any).lastAutoTable.finalY + 8
  const deductionsData = deductions.map(d => [d.type, `₹${d.amount.toLocaleString()}`])
  autoTable(doc, {
    startY: afterEarnings,
    head: [["Deductions", "Amount (₹)"]],
    body: [...deductionsData, ["Total Deductions", `₹${totalDeductions.toLocaleString()}`]],
    theme: "grid",
    headStyles: { fillColor: [30, 64, 175], halign: "center", textColor: 255 },
    styles: { fontSize: 10, halign: "center" },
  })

  // --- NET PAY SECTION ---
  const afterDeductions = (doc as any).lastAutoTable.finalY + 12
  doc.setFontSize(12)
  doc.setFont("helvetica", "bold")
  doc.setDrawColor(30, 64, 175)
  doc.setFillColor(230, 240, 255)
  doc.rect(14, afterDeductions - 6, 182, 12, "FD")
  doc.setTextColor(30, 64, 175)
  doc.text("Net Pay", 20, afterDeductions + 2)
  doc.text(`₹${netPay.toLocaleString()}`, 190, afterDeductions + 2, { align: "right" })

  // --- FOOTER ---
  doc.setTextColor(100)
  doc.setFontSize(9)
  doc.text(
    "This is a computer-generated payslip and does not require a signature.",
    105,
    285,
    { align: "center" }
  )
  doc.text("Generated by ACME HRMS Portal", 105, 291, { align: "center" })

  // --- SAVE ---
  doc.save(`${employee.name}-Payslip.pdf`)
}

  const Section = ({ title, children }: { title: string; children: React.ReactNode }) => {
    const [open, setOpen] = React.useState(false)
    return (
      <Collapsible.Root open={open} onOpenChange={setOpen}>
        <Collapsible.Trigger asChild>
          <Button
            variant="outline"
            className="w-full flex justify-between items-center mt-4"
          >
            {title}
            <ChevronDown
              className={`transition-transform duration-300 ${open ? 'rotate-180' : ''}`}
            />
          </Button>
        </Collapsible.Trigger>
        <Collapsible.Content>
          <div className="mt-2">{children}</div>
        </Collapsible.Content>
      </Collapsible.Root>
    )
  }

  return (
    <div className="min-h-screen bg-gray-50 p-8">
      {/* Breadcrumb */}
      <div className="flex items-center text-lg text-muted-foreground px-5 py-3 bg-card rounded-xl shadow-sm border border-border mb-6">
        <Link href="/hrms" className="font-medium hover:text-primary transition-colors">
          HRMS
        </Link>
        <span className="mx-2 text-border">/</span>
        <Link href="/hrms/ess" className="font-medium hover:text-primary transition-colors">
         Ess
        </Link>
        <span className="mx-2 text-border">/</span>
        <span className="text-foreground font-semibold">My Payslip</span>
      </div>
    <div className="max-w-3xl mx-auto my-8">
      <Card className="p-6 shadow-lg border border-gray-200">
        {/* Header */}
        <div className="flex justify-between items-center mb-6">
          <h1 className="text-2xl font-bold text-blue-700">Payslip</h1>
          <Button
            className="bg-blue-700 text-white hover:bg-blue-800"
            onClick={handleDownloadPDF}
          >
            Download PDF
          </Button>
        </div>

        {/* Employee Info */}
        <div className="bg-gray-50 p-4 rounded-md border border-gray-200">
          <h2 className="text-lg font-semibold text-gray-700 mb-2">Employee Information</h2>
          <div className="grid grid-cols-2 gap-4 text-gray-600">
            <p><strong>Name:</strong> {employee.name}</p>
            <p><strong>Employee ID:</strong> {employee.id}</p>
            <p><strong>Designation:</strong> {employee.designation}</p>
            <p><strong>Department:</strong> {employee.department}</p>
            <p><strong>Joining Date:</strong> {employee.joiningDate}</p>
          </div>
        </div>

        {/* Collapsible Sections */}
        <Section title="Earnings">
          <table className="w-full text-left border border-gray-200">
            <thead className="bg-blue-100">
              <tr>
                <th className="px-4 py-2">Type</th>
                <th className="px-4 py-2">Amount (₹)</th>
              </tr>
            </thead>
            <tbody>
              {earnings.map((e, idx) => (
                <tr key={idx} className="border-t border-gray-200">
                  <td className="px-4 py-2">{e.type}</td>
                  <td className="px-4 py-2">{e.amount.toLocaleString()}</td>
                </tr>
              ))}
              <tr className="font-bold border-t border-gray-300">
                <td className="px-4 py-2">Total Earnings</td>
                <td className="px-4 py-2">{totalEarnings.toLocaleString()}</td>
              </tr>
            </tbody>
          </table>
        </Section>

        <Section title="Deductions">
          <table className="w-full text-left border border-gray-200">
            <thead className="bg-blue-100">
              <tr>
                <th className="px-4 py-2">Type</th>
                <th className="px-4 py-2">Amount (₹)</th>
              </tr>
            </thead>
            <tbody>
              {deductions.map((d, idx) => (
                <tr key={idx} className="border-t border-gray-200">
                  <td className="px-4 py-2">{d.type}</td>
                  <td className="px-4 py-2">{d.amount.toLocaleString()}</td>
                </tr>
              ))}
              <tr className="font-bold border-t border-gray-300">
                <td className="px-4 py-2">Total Deductions</td>
                <td className="px-4 py-2">{totalDeductions.toLocaleString()}</td>
              </tr>
            </tbody>
          </table>
        </Section>

        <Section title="Net Pay">
          <div className="p-4 bg-blue-50 rounded-md text-blue-700 font-bold text-xl">
            ₹{netPay.toLocaleString()}
          </div>
        </Section>
      </Card>
    </div>
    </div>
  )
}
